version: '3.8'

services:
  postgres:
    image: postgres:latest
    # fetch .env
    env_file:
      - .env
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASS}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '${DB_PORT}'

